#!/bin/bash

commandName="${0##*/}"
function helpInfo(){
    cat <<!
        command:
            $commandName -s size -f file [-d delimiter] [file]

        说明：
            多行合并成少行

        参数：
            -s      多少行合并成一行
            -f      要操作的文件
            -d      合并后的每行分隔符(默认,)
            -S      从标准输入或者管道获取数据

        example:
            $commandName -s 10 -d',' -f x.txt
!
}

function standardSource(){
    local size="$1"
    local delimiter="$2"
    local i=0
    local isNotRowFirst=false
    while read -r row;do
        if [[ "$row" == "" ]];then
            continue
        fi
        ((i++))
        if $isNotRowFirst ;then
            echo -n "${delimiter}"
        fi
        echo -n "${row}"
        local temp=$(($i % $size))
        if ((0 == $temp));then
            isNotRowFirst=false
            echo ""
        else
            isNotRowFirst=true
        fi
    done
    echo ""
    return 0
}

function fileSource(){
    local size="$1"
    local delimiter="$2"
    local file="$3"
    if [[ "$file" == "" ]];then
        file="$1"
    fi
    if [[ "$file" == "" ]];then
        echo "缺少文件参数" >&2
    fi

    local i=0
    local isNotRowFirst=false
    for row in $(cat "$file");do
        if [[ "$row" == "" ]];then
            continue
        fi
        ((i++))
        if $isNotRowFirst ;then
            echo -n "${delimiter}"
        fi
        echo -n "${row}"
        local temp=$(($i % $size))
        if ((0 == $temp));then
            isNotRowFirst=false
            echo ""
        else
            isNotRowFirst=true
        fi
    done
    echo ""
    return 0
}

function main(){
    local file=""
    local size=""
    local delimiter=","
    local isStandardIn=false
    OPTIND=1
    while getopts ":s:f:d:-:hS" opt;do
        case "$opt" in
            d)
                delimiter="$OPTARG"
                ;;
            f)
                file="$OPTARG"
                ;;
            s)
                size="$OPTARG"
                if ! [[ "$size" =~ ^[0-9]+$ ]];then
                    echo "参数 -s 的值必须是数字"
                    exit 1
                fi
                ;;
            h)
                helpInfo
                exit 0
                ;;
            S)
                isStandardIn=true
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        helpInfo
                        exit 0
                        ;;
                esac
                ;;
            :)
                echo "参数 -${OPTARG} 缺少值" >&2
                exit 1
                ;;
            \?)
                echo "参数 -${OPTARG} 不认识" >&2
                exit 1
                ;;
            *)
                exit 1
                ;;
        esac
    done
    shift $(($OPTIND-1))

    if [[ "$size" == "" ]];then
        echo "$commandName 缺少尺寸参数-s" >&2
        exit 1
    fi

    if $isStandardIn ;then
        standardSource "$size" "$delimiter"
    else
        if [[ "$file" == "" ]];then
            file="$1"
        fi
        if [[ "$file" == "" ]];then
            echo "$commandName 缺少文件参数-f或标准输入" >&2
            exit 1
        fi
        fileSource "$size" "$delimiter" "$file"
    fi
}

main "$@"

