#!/bin/bash

declare -r COMMAND_NAME="$(basename "$0")"
declare -r DIR_NAME="$(basename "$PWD")"

declare IsRestrictMasterBranch=true
declare -a MasterBranchList=("master" "main")

function helpInfo(){
    cat <<!

        command:$COMMAND_NAME
            $COMMAND_NAME [-sjvr] [ --jenkins | --rule-prefix ] "CommitInfo"

        参数：
            -s / --self         只提交到当前分支，不进行切换分支
            -j / --jenkins      把commit_id作为参数,传递给jenkins命令
            --jenkins_xxx=xxx   把xxx=xxx作为参数,传递给jenkins命令,例如：--jenkins_restart=restart-0259
            -v                  使用VPN连接执行命令，执行完成后断开VPN连接
                                    目前支持的VPN类型有：
                                        Cisco AnyConnect Secure Mobility Client
            -r / --rule-prefix  指定前缀的分支合并到指定分支上,如果没有设置则目标分支默认为${COMMAND_NAME}分支
                                    格式如：-r dev_:dev,dev2_:dev2 表示以dev_和dev2_开头的分支分别合并到dev和dev2分支上

        说明：
            会把git的"当前分支"合并到"${COMMAND_NAME}"开发分支
            如果想变更要合并的开发分支，修改脚本名称即可
        
        环境变量：
            CISCO_ANYCONNECT_VPN_ADDRESS     Cisco AnyConnect VPN连接的服务器地址
                                             手动配置例如：export CISCO_ANYCONNECT_VPN_ADDRESS=http://example.com
                                             第一次链接成功后会自动保存到环境变量里
                                             如果想删除,直接删除环境变量或者删除对应的配置行即可
                                             环境变量位置：
                                                 Linux: ~/.bashrc
                                                 MacOS: ~/.zshrc
            MASTER_BRANCH_LIST               受限制的主分支列表，默认值为"master main"
                                             如果需要修改，设置环境变量覆盖即可，多个分支使用空格分隔
                                                例如：export MASTER_BRANCH_LIST="master main branch1 branch2"
            DEVELOPMENT_MERGE_RULE_PREFIX    合并分支规则前缀，格式为 prefix1:targetBranch1,prefix2:targetBranch2
                                             如果设置了这个环境变量，在执行脚本时会根据当前分支名匹配对应的前缀，找到目标分支进行合并
                                             也可以通过命令行参数--rule-prefix临时指定规则前缀，优先级高于环境变量
                                                例如：export DEVELOPMENT_MERGE_RULE_PREFIX="dev-:dev,feature-:feature"
                                                      表示以dev-和feature-开头的分支分别合并到dev和feature分支上

        example:
            $COMMAND_NAME "提交并且合并到${COMMAND_NAME}分支"
            $COMMAND_NAME -s "只提交到当前分支"
            $COMMAND_NAME -v --rule-prefix=dev-:dev "以dev-开头的分支合并到dev分支上，并且使用VPN连接执行命令"

!
    exit 0
}

envParamsArgs=""
if [[ -f .development_merge_params ]]; then
    envParamsArgs=$(cat .development_merge_params)
fi

set -- $envParamsArgs "$@"

declare IsPostJenkins=false
declare OnlyPushSelf=false
declare IsVPN=false
declare -a JenkinsParams=()
declare RulePrefix=""
declare MergeBranch=""  # 功能完善有待商议
declare MergeRequest="" # 功能完善有待商议
OPTIND=1
while getopts ":r:m:M:-:jshv" opt;do
    case "$opt" in
        s)
            OnlyPushSelf=true
            ;;
        h)
            helpInfo
            ;;
        j)
            IsPostJenkins=true
            ;;
        v)
            IsVPN=true
            ;;
        r)
            RulePrefix="$OPTARG"
            ;;
        m)
            MergeBranch="$OPTARG"
            ;;
        M)
            MergeRequest="$OPTARG"
            ;;
        -)
            argKeyLong=${OPTARG%%=*}
            if [[ "$OPTARG" =~ = ]];then
                case "$argKeyLong" in
                    "rule-prefix")
                        RulePrefix="${OPTARG#*=}"
                        ;;
                    *)
                        if [[ "$argKeyLong" =~ ^jenkins_ ]];then
                            JenkinsParams+=("--${OPTARG#jenkins_}")
                        fi
                        ;;
                esac
                continue
            else
                case "$argKeyLong" in
                    "help")
                        helpInfo
                        ;;
                    "jenkins")
                        IsPostJenkins=true
                        ;;
                    "self")
                        OnlyPushSelf=true
                        ;;
                    "not-restrict-master-branch")
                        IsRestrictMasterBranch=false
                        ;;
                    *)
                        ;;
                esac
                continue
            fi
        ;;
    esac
done
shift $(($OPTIND-1))

declare DevelopmentBranch="$COMMAND_NAME"

declare -r COMMIT_INFO="$1"
if [[ "$COMMIT_INFO" == "" ]];then
    echo "input commit info"
    exit 1
fi

function printFormat(){
    local data="$1"
    local currentBranchNameTemp
    currentBranchNameTemp=$(git_current_branch) || {
        return 1
    }
    local commandPrefix="\033[32m[$(date '+%F %T')] \033[36m$DIR_NAME\033[32m (\033[31;1m$currentBranchNameTemp\033[0;32m)\033[1m ➜ \033[0m"
    echo -e "${commandPrefix}\033[33m$data\033[0m"
}

function getEnv(){
    local envName="$1"
    if [[ -z "$envName" ]];then
        echo ""
        return 0
    fi
    envVal="${!envName}"
    if [[ -z "$envVal" ]];then
        local bashName=$(basename "$SHELL")
        if [[ "$bashName" == "bash" ]] && [[ -f ~/.bashrc ]] ;then
            envVal=$(grep "$envName" ~/.bashrc | tail -n1 | awk -F'[ =]+' '{print $NF}')
        fi
        if [[ "$bashName" == "zsh" ]] && [[ -f ~/.zshrc ]];then
            envVal=$(grep "$envName" ~/.zshrc | tail -n1 | awk -F'[ =]+' '{print $NF}')
        fi
    fi
    echo "$envVal"
    return 0
}

function setEnvIfEmpty(){
    local envName="$1"
    local envVal="$2"
    if [[ -z "$envName" ]] || [[ -z "$envVal" ]];then
        return 0
    fi
    if [[ -n "$(getEnv "$envName")" ]];then
        return 0
    fi
    local bashName=$(basename "$SHELL")
    local bashPath=""
    if [[ "$bashName" == "bash" ]];then
        bashPath="$HOME/.bashrc"
    elif [[ "$bashName" == "zsh" ]];then
        bashPath="$HOME/.zshrc"
    fi
    echo "export $envName=$envVal" >> "$bashPath"
}

function getCurrentBranchName(){
    local branchList
    local grepList
    local currentBranchName
    branchList=$(git branch) || {
        return 11
    }
    grepList=$(echo "$branchList" | grep "*") || {
        echo "grep no find branch" >&2
        return 12
    }
    currentBranchName=$(echo "$grepList" | awk '{print $2}')
    if [[ "$currentBranchName" == "" ]] ;then
        echo "awk no find branch name" >&2
        return 13
    fi
    echo "$currentBranchName"
    return 0
}

function git_current_branch() {
  local ref
  ref=$(git symbolic-ref --quiet HEAD 2> /dev/null)
  local ret=$?
  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && {
        return 21 # no git repo.
    }
    ref=$(git rev-parse --short HEAD 2> /dev/null) || {
        return 22
    }
  fi
  echo ${ref#refs/heads/}
}

function getDevelopmentBranchByRulePrefix(){
    local rulePrefixData=""
    local tempData=""
    if [[ -n "$RulePrefix" ]];then
        rulePrefixData="$RulePrefix"
        tempData="参数传递的规则前缀"
    elif [[ -n "$DEVELOPMENT_MERGE_RULE_PREFIX" ]];then
        rulePrefixData="$DEVELOPMENT_MERGE_RULE_PREFIX"
        tempData="环境变量的规则前缀"
    fi
    if [[ "$rulePrefixData" == "" ]];then
        printFormat "未设置规则前缀，默认合并到${DevelopmentBranch}分支"
        return 0
    fi
    for val in $(echo "$rulePrefixData" |tr ',' '\n');do
        if [[ "$val" != *:* ]];then
            echo  >&2 "--rule-prefix=$val 格式错误, 格式需是： prefix1:targetBranch1,prefix2:targetBranch2"
            return 1
        fi
        local prefix="${val%%:*}"
        local targetBranch="${val#*:}"
        if [[ "$prefix" != "" ]] && [[ "$targetBranch" != "" ]];then
            if [[ "$(git_current_branch)" == "$prefix"* ]];then
                printFormat "当前分支匹配到了${tempData}${prefix}，合并到${targetBranch}分支"
                DevelopmentBranch="$targetBranch"
                return 0
            fi
        fi
    done
    printFormat "当前分支没有匹配到任何规则前缀，默认合并到${DevelopmentBranch}分支"
    return 0
}

function isInMasterBranchList(){
    local currentBranchName="$1"
    if [[ -n "$MASTER_BRANCH_LIST" ]];then
        for v in $MASTER_BRANCH_LIST ;do
            if [[ "$currentBranchName" == "$v" ]];then
                return 0
            fi
        done
        return 1
    fi
    for v in ${MasterBranchList[@]} ;do
        if [[ "$currentBranchName" == "$v" ]];then
            return 0
        fi
    done
    return 1
}

declare -r VPN_LIST=(
    "/opt/cisco/anyconnect/bin/vpn:ciscoAnyconnectVPN_func"
    # "openvpnLogin:openvpn_func"
)
declare -r VPN_STSTUS_ON="on"
declare -r VPN_STSTUS_OFF="off"
declare VpnCurrentStatus=false
declare VpnCurrentAppIsOpen=false

function ciscoAnyconnectVPN_func() {
    local envName="CISCO_ANYCONNECT_VPN_ADDRESS"
    local vpnAppName="Cisco AnyConnect Secure Mobility Client"
    local vpnFuncPath="$1"
    local vpnStatus="$2"
    if ! $(command -v "$vpnFuncPath" > /dev/null 2>&1);then
        echo >&2 "命令未找到：$vpnFuncPath"
        return 1
    fi
    if [[ "$vpnStatus" != "$VPN_STSTUS_ON" ]] && [[ "$vpnStatus" != "$VPN_STSTUS_OFF" ]];then
        echo >&2 "状态错误：请输入VPN状态：on/off"
        return 2
    fi
    local errorCountNum=0
    vpnAddress="$(getEnv "$envName")"
    if [[ "$vpnAddress" == "" ]];then
        while read -p "请输入VPN连接的服务器地址:" -r vpnServerAddress ;do
            if [[ "$vpnServerAddress" != "" ]];then
                vpnAddress="$vpnServerAddress"
                break
            fi
            ((errorCountNum++))
            if ((errorCountNum >= 3));then
                echo >&2 "输入错误次数过多，退出"
                return 1
            fi
        done
    fi
    local actionCmd="connect"
    if [[ "$vpnStatus" == "$VPN_STSTUS_OFF" ]];then
        actionCmd="disconnect"
    fi
    currentBranchNameTemp=$(git_current_branch) || {
        return 1
    }

    if [[ "$vpnStatus" == "$VPN_STSTUS_ON" ]];then
        local vpnStatusMsg=$($vpnFuncPath stats|grep 'Connection State' |grep -v Management|awk -F'[: ]+' '{print $NF}')
        if [[ "$vpnStatusMsg" == "Connected" ]];then
            VpnCurrentStatus=true
            printFormat "VPN 已连接，无需重复连接"
            return 0
        fi
        if [[ "$vpnStatusMsg" == "Disconnected" ]];then
            ps -ef | grep "$vpnAppName" | grep -v 'grep' > /dev/null 2>&1 && {
                pkill -f "$vpnAppName" && {
                    printFormat "VPN 软件已打开但是未链接，尝试关闭图形客户端"
                    VpnCurrentAppIsOpen=true
                }
            }
        fi
    elif ${VpnCurrentStatus} && [[ "$vpnStatus" == "$VPN_STSTUS_OFF" ]];then
        printFormat "VPN 原本就是已连接状态，无需执行断开连接操作"
        return 0
    fi

    printFormat "${vpnFuncPath} ${actionCmd} ${vpnAddress}"
    $vpnFuncPath "$actionCmd" "$vpnAddress"

    if ${VpnCurrentAppIsOpen} && [[ "$vpnStatus" == "$VPN_STSTUS_OFF" ]];then
        printFormat "VPN 尝试打开图形客户端软件"
        open -a "$vpnAppName"
    fi

    if [[ "${!envName}" == "" ]];then
        local vpnStatusMsg=$($vpnFuncPath stats|grep 'Connection State' |grep -v Management|awk -F'[: ]+' '{print $NF}')
        if [[ "$vpnStatusMsg" == "Connected" ]];then
            setEnvIfEmpty "$envName" "$vpnAddress"
        fi
    fi
}

function openvpn_func() {
    echo ""
}

function useVPN() {
    if ! $IsVPN ;then
        return 0
    fi
    local vpnStatus="$1"
    if [[ "$vpnStatus" != "$VPN_STSTUS_ON" ]] && [[ "$vpnStatus" != "$VPN_STSTUS_OFF" ]];then
        echo >&2 "状态错误：请输入VPN状态：on/off"
        return 2
    fi
    local availableVpnList=()
    for v in ${VPN_LIST[@]};do
        cmdStr="${v%:*}"
        if command -v "$cmdStr" > /dev/null 2>&1;then
            availableVpnList+=("$cmdStr")
        fi
    done
    local vpnFuncInfo=""
    if [[ "${#availableVpnList[@]}" == "1" ]];then
        vpnFuncInfo="${VPN_LIST[0]}"
    else
        local k=0
        for val in ${availableVpnList[@]} ;do
            ((k++))
            printf " %s\t%s\n" "$k" "$val"
        done
        local errorCountNum=0
        while read -p "请选择VPN连接（输入序号[1-${#availableVpnList[@]}]）:" -r vpnIndex ;do
            if [[ "${vpnIndex}" =~ ^[1-9]+$ ]];then
                vpnFuncInfo="${VPN_LIST[$vpnIndex-1]}"
                if [[ "$vpnFuncInfo" != "" ]];then
                    break
                fi
            fi
            ((errorCountNum++))
            if ((errorCountNum >= 3));then
                echo >&2 "输入错误次数过多，退出"
                return 1
            fi
        done
    fi
    local vpnFuncName="${vpnFuncInfo#*:}"
    local vpnFuncPath="${vpnFuncInfo%:*}"
    $vpnFuncName "$vpnFuncPath" "$vpnStatus"
}

function mergeDevelopmentBranch(){
    local currentBranchName
    currentBranchName=$(git_current_branch) || {
        local tempCode="$?"
        if [[ "$tempCode" == "21" ]];then
            echo "not a git repository"
        fi
        return $tempCode
    }

    getDevelopmentBranchByRulePrefix || {
        return 1
    }

    if [[ "$currentBranchName" == "$DevelopmentBranch" ]];then
        echo "current is target development branch"
        return 1
    fi
    if $IsRestrictMasterBranch ;then
        isInMasterBranchList "$currentBranchName" && {
            while read -p "当前正在操作${currentBranchName}分支，是否继续操作：(N/y):" -r row ;do
                if [[ "$row" == "N" || "$row" == "n" || "$row" == "" ]];then
                    echo "exit"
                    return 0
                fi
                if [[ "$row" == "Y" || "$row" == "y" ]];then
                    break;
                fi
            done
        }
    fi
    local execList
    local gitLogOne="git --no-pager log --no-color -n 1"
    execList=(
        "git --no-pager diff"
        "git add -A"
        "git commit -m '$COMMIT_INFO'"
        "git pull"
        "git push"
        "git checkout $DevelopmentBranch"
        "git pull"
        "git merge $currentBranchName -m 'Merge branch $currentBranchName into $DevelopmentBranch'"
        "git push"
        "$gitLogOne"
        "git checkout $currentBranchName"
    );
    if $OnlyPushSelf ;then
        execList=(
            "git --no-pager diff"
            "git add -A"
            "git commit -m '$COMMIT_INFO'"
            "git pull"
            "git push"
        );
    fi
    local implemented
    local commitId=""
    local currentBranchNameTemp
    for commandStr in "${execList[@]}" ;do
        if [[ "$implemented" == "$commandStr" ]];then
            continue
        fi
        implemented="$commandStr"
        dateTime=$(date '+%F %T')
        currentBranchNameTemp=$(git_current_branch) || {
            return 1
        }
        printFormat "$commandStr"

        if [[ "$commandStr" == "$gitLogOne" ]];then
            commitId=$(eval "$commandStr" | head -n1 | awk '{print $2}')
        fi

        eval "$commandStr" || {
            echo ""
            echo -e "Execution Failed"
            echo -e "   Solution:"
            echo -e "       • p: Push Again    "
            echo -e "       • s: Skip          "
            echo -e "       • e: Exit          "
            str=$(echo -e  "\033[31;1mSelect Execution(p/s or e):\033[0m")
            while read -p "$str" -r row ;do
                if [[ "$row" == "e" || "$row" == "E" ]];then
                    return 1
                elif [[ "$row" == "s" || "$row" == "S" ]];then
                    break
                elif [[ "$row" == "p" || "$row" == "P" ]];then
                    local conflictExecList=(
                        "git add -A"
                        "git commit -m 'resolve the conflict：$COMMIT_INFO'"
                        "git pull"
                        "git push"
                    )
                    for val in "${conflictExecList[@]}" ;do
                        dateTime=$(date '+%F %T')
                        implemented="$val"
                        printFormat "$val"
                        eval "$val" || {
                            return 1
                        }
                    done
                    break
                else
                    continue
                fi
            done
        }
    done
    if $IsPostJenkins ;then
        if [[ "$commitId" != "" ]];then
            currentBranchNameTemp=$(git_current_branch) || {
                return 1
            }
            declare params=""
            for v in "${JenkinsParams[@]}"; do
                params="${params} $v"
            done
            local evalStr="jenkins \"$commitId\""
            if [[ "$params" != "" ]];then
                evalStr="jenkins${params} \"$commitId\""
            fi
            printFormat "$evalStr"
            eval "$evalStr"
        fi
    fi
}

function main(){
    local retCode=0
    useVPN "$VPN_STSTUS_ON"
    mergeDevelopmentBranch || {
        retCode=1
    }
    useVPN "$VPN_STSTUS_OFF"
    return $retCode
}

main
