#!/bin/bash

configInit=$(cat <<!
# username=xxxx
# appToken=xxxx
# url=https://test-jenkins.xxxx.com
# 目录和pod name的对应关系
# podNameList=(
#     wm-light-backend=k8s-test-php-backend-new
#     wm-light-frontend=k8s-test-php-frontend-new
# )
# 目录和发布参数的对应关系
# paramList=(
#     wm-backend=backend_version
#     wm-backend=title
#     wm-frontend=frontend_version
# )
!
)

configPath="$HOME/.config/jenkins/.jenkinsrc"

declare -r dirName="$(basename "$(pwd)")"

timeTemp="$(date +'%s')"

function helpInit(){
    cat <<!
        command [-c] commitId

        第一次执行会自动生产一个配置文件:
            1.配置文件路径："$configPath"
            2.编辑该配置文件后就可以使用了

        参数：
            -c commitId(默认选项)

!
    exit 0
}


if [ ! -f "$configPath" ];then
    if [ ! -d "$(dirname "$configPath")" ];then
        mkdir -p "$(dirname "$configPath")"
    fi
    echo "$configInit" > "$configPath"
fi

. "$configPath"

function main(){
    local commitId=""
    OPTIND=1
    while getopts ':c:h' opt;do
        case "$opt" in
            c)
                commitId="$OPTARG";;
            h)
                helpInit
                ;;
        esac
    done
    shift $(($OPTIND-1))

    if [[ "$username" == "" ]] || [[ "$appToken" == "" ]] || [[ "$url" == ""  ]] || [[ "$podNameList" == "" ]] || [[ "$paramList" == "" ]];then
        echo "请先编辑配置文件：$configPath"
        exit 0
    fi


    if [[ "$commitId" == "" ]];then
        commitId="$1"
    fi

    if [[ "$commitId" == "" ]];then
        echo >&2 "commitId 不能为空"
        exit 1
    fi
    local params=""
    for v in "${paramList[@]}";do
        local name="${v%%=*}"
        local paramKey="${v#*=}"
        if [[ "$name" != "$dirName" ]];then
            continue
        fi
        params="${params} --form '${paramKey}=\"${commitId}\"'"
    done

    local podList=()
    local podListIndex=0
    local execStr=""
    for v in "${podNameList[@]}";do
        local name="${v%%=*}"
        local podName="${v#*=}"
        if [[ "$name" != "$dirName" ]];then
            continue
        fi
        execStr="curl -X POST -u ${username}:${appToken} ${url}/job/${podName}/buildWithParameters ${params}"
        echo "$execStr"
        eval "$execStr"
        podList[$podListIndex]="${podName}"
        podListIndex=$(($podListIndex+1))
    done
    if [[ "$execStr" == "" ]];then
        echo "没有匹配到要构建的指令"
        exit 0
    fi

    progressPod "${podList[@]}"
    exit 0
}

function progressPodListFun(){
    if [[ "$podList" == "" ]];then
        return 0
    fi
    local progressPodList=()
    local progressIndex=0
    for v in "${podList[@]}";do
        local execStr="curl -s -X POST -u ${username}:${appToken} '${url}/job/${v}/lastBuild/api/json?pretty=true' | jq '.number'"
        local buildNumber="$(eval "$execStr")"
        progressPodList[$progressIndex]="${v}/${buildNumber}"
        progressIndex=$(($progressIndex+1))
    done
    echo ${progressPodList[@]}
}

# ret code: 
#    11 continue
#    12 exit
#    13 error
function progressFmt(){
    local temp="$1"
    local building
    local estimatedDuration
    local timestamp
    local result
    local isJqError=true
    building="$(echo "$temp" | jq '.building')" && {
        isJqError=false
    }
    estimatedDuration="$(echo "$temp" | jq '.estimatedDuration')" && {
        isJqError=false
    }
    timestamp="$(echo "$temp" | jq -r '.timestamp')" && {
        isJqError=false
    }
    result="$(echo "$temp" | jq -r '.result')" && {
        isJqError=false
    }
    if $isJqError ;then
        echo >&2 "$temp"
        echo >&2 "数据解析失败,不是一个有效的json"
        return 13
    fi
    if [[ "$timestamp" == "" ]];then
        printf "\r没有获取到时间%s        " "${point}."
        return 11
    fi
    if (( $timestamp > 9000000000 ));then
        timestamp=$(($timestamp/1000))
    fi
    if (($timestamp < $timeTemp));then
        local point=""
        for ((i=0;i<($v%6);i++)) ;do
            point="${point}."
        done
        printf "\r正在获取中%s        " "${point}."
        return 11
    fi
    local now="$(date +'%s')"
    local durationTime=$(($now-$timeTemp))
    local proportionNum="$((100000*$durationTime/$estimatedDuration))"
    if (($proportionNum > 100)) ;then
        proportionNum=99
    fi
    if [[ "$result" == "SUCCESS" ]];then
        proportionNum=100
    fi
    resultTemp="$result"
    if [[ "$resultTemp" == "null" ]];then
        resultTemp="ing..."
    fi
    local strTempCurrent="[${v2}]:【${durationTime}s】【${proportionNum}％】【${resultTemp}】"
    printf "${strTempCurrent}"
    if [[ "$result" == "null" ]];then
        return 0
    fi
    return 12
}

function progressPod() {
    sleep 2
    declare -a progressPodList=($(progressPodListFun $@))
    if [[ "$progressPodList" == "" ]];then
        return 0
    fi
    local isExit=false
    local endStr=""
    local v2Index=0
    declare -a progressRet=()
    for v in {1..500};do
        local strTemp=""
        local isContinue=false
        local tempNum="${#progressPodList[@]}"
        v2Index=0
        for v2 in ${progressPodList[@]};do
            isContinue=false
            local strTempCurrent="${progressRet[$v2Index]}"
            if [[ "$strTempCurrent" == "" ]];then
                local execStr="curl -s -X POST -u ${username}:${appToken} '${url}/job/${v2}/api/json?pretty=true'"
                local temp="$(eval "$execStr")"
                strTempCurrent=$(progressFmt "$temp")
                statusProgressFmt="$?"
            fi
            case "$statusProgressFmt" in
                11)
                    isContinue=true
                    printf "\r${strTempCurrent}"
                    break
                    ;;
                12)
                    progressRet[$v2Index]="$strTempCurrent"
                    tempNum=$(($tempNum-1))
                    if (($tempNum<=0));then
                        isExit=true
                    fi
                    ;;
                13)
                    exit 3
                    ;;
                *)
                    ;;
            esac
            if (($v2Index>0));then
                endStr="${endStr} \033[1B"
            fi
            v2Index=$(($v2Index+1))
            if [[ "$strTemp" == "" ]];then
                strTemp="${strTempCurrent}"
            else
                strTemp="${strTemp}\n${strTempCurrent}\033[1A"
            fi
        done
        printf "\r${strTemp}"
        if $isExit ;then
            break
        fi
        if $isContinue ;then
            sleep 2
            progressPodList=$(progressPodListFun "$1")
            if [[ "$progressPodList" == "" ]];then
                return 0
            fi
            continue
        fi
        sleep 2
    done
    printf "${endStr}\n"
    return 0
}

    # podList=("k8s-test-php-wm-light-frontend-new" "k8s-test-php-wm-light-frontend-supervisor-crontab")
    # progressPod "${podList[@]}"
    # exit 1

main $@
